### ISSUE TITLE
Plugin doesn't work

### ISSUE THREAD

**Issue by Askoltik** [jtydhr88/eagle-ai-tagger#1]
I guess it's broke. That's happen when i select some image and open AI Tagger
4.0.0 Build2
![image](https://github.com/user-attachments/assets/cc8b221d-3bae-4cf4-a482-5173398ae5ce)

**Comment by jtydhr88** [comment]
Can you press F12 while the plugin opened, and take a screenshot for full log in the console?

**Comment by Askoltik** [comment]
Yeah sure.

![image](https://github.com/user-attachments/assets/83d493fa-0431-49a5-99c3-78e66c7693cc)

**Comment by jtydhr88** [comment]
Have you installed nodejs and run node install in the plugin folder? Please follow the readme

**Comment by Askoltik** [comment]
I followed, but i got this stuff
![image](https://github.com/user-attachments/assets/b0627c6f-2c2a-4b15-a33f-ce2e90a2d7bf)

**Comment by Askoltik** [comment]
So ok,  i fixed that bug by this command.

` npm install onnxruntime-node`

**Comment by jtydhr88** [comment]
Sorry, I just notice I wrote a wrong command in readme, you are right, it should be npm install

**Comment by Askoltik** [comment]
resolved
